export {
  BoardEntryCard,
  ControlDeck,
  CompactMetric,
  EmptyState,
  EntryNote,
  MetaChip,
  MetricTile,
  NarrativePanel,
  OpsSignalTile,
  SectionHeader,
  StatusSidebar,
  StatusField,
  SystemBoard,
  TonePill,
  TrendSparkline,
  WatchlistItem,
  WatchlistPanel,
} from "@/views/system/components/dashboardPrimitives"
