
APP_ID = "LearningPyramid"
APP_NAME = "LearningPyramid"
APP_PACKAGE_NAME = APP_ID
LAUNCHER_EXE_BASENAME = APP_ID
STOP_EXE_BASENAME = f"{APP_ID}-stop"
SERVER_EXE_BASENAME = f"{APP_ID}-server"
APP_VERSION = "0.1.0-beta.3"
